# Generated by Django 5.0.3 on 2024-03-29 12:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='user',
        ),
        migrations.AddField(
            model_name='retailer',
            name='address',
            field=models.TextField(default='Default Address'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='contact_number',
            field=models.CharField(default='Default Contact Number', max_length=20),
        ),
        migrations.AddField(
            model_name='retailer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='retailer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retailer',
            name='name',
            field=models.CharField(default='Default Retailer Name', max_length=200),
        ),
        migrations.AddField(
            model_name='retailer',
            name='pincode',
            field=models.CharField(default='Default Pincode', max_length=10),
        ),
        migrations.AddField(
            model_name='retailer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
