# Generated by Django 5.0.3 on 2024-03-29 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
        ('users', '0004_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PI', 'Pending Invoice'), ('PP', 'Pending Payment'), ('PD', 'Paid')], default='PI', max_length=2)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.dealer')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.retailer')),
                ('sales_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.TextField()),
                ('customer_id', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=15)),
                ('waybill_number', models.CharField(max_length=255)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('courier_name', models.CharField(max_length=255)),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('PD', 'Paid'), ('O', 'Overdue')], default='P', max_length=2)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.color')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.size')),
            ],
        ),
    ]
