# Generated by Django 5.0.3 on 2024-04-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('PA', 'Pending Approval'), ('I', 'Invoice Generated'), ('PI', 'Pending Invoice'), ('PD', 'Paid'), ('PP', 'Pending Payment'), ('S', 'Shipped'), ('D', 'Delivered'), ('RI', 'Return Initiated'), ('RC', 'Return Completed'), ('R', 'Refunded')], default='PP', max_length=2),
        ),
    ]
