# Generated by Django 5.0.3 on 2024-03-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
