# Generated by Django 5.0.3 on 2024-03-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_purchase_products_purchase_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
