# Generated by Django 5.0.3 on 2024-03-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_color_size_colorgroup_sizegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_code',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
