# Generated by Django 5.0.3 on 2024-03-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_size_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorgroup',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='sizegroup',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='ColorGroup',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='SizeGroup',
        ),
    ]
